### PR TITLE
Adds openapi spec for POST /api/v2/spans including the json format

### PR DESCRIPTION
**Pull request by adriancole**
See https://github.com/openzipkin/zipkin/issues/1499 for the description of this format

I tested this with a deviation of @devinsba example here: https://github.com/openzipkin/zipkin-api-example/pull/1

```go
package main

import (
	"fmt"
	"log"
	"math/rand"
	"strconv"
	"time"

	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/openzipkin/zipkin-api-example/go/client"
	"github.com/openzipkin/zipkin-api-example/go/client/operations"
	"github.com/openzipkin/zipkin-api-example/go/models"
)

func main() {
	transport := httptransport.New("localhost:9411", "/api/v2", []string{"http"})
	zipkin := client.New(transport, strfmt.Default)

	id := uint64(rand.New(rand.NewSource(time.Now().UnixNano())).Int63())
	spanID := strconv.FormatUint(id, 16)
	timestamp := int64(time.Now().UnixNano() / int64(time.Microsecond))
	span := &models.Span{
		TraceID:   spanID,
		ID:        spanID,
		Kind:      models.SpanKindSERVER,
		Name:      "test",
		Timestamp: timestamp,
		Duration:  int64(200000),
		LocalEndpoint: &models.Endpoint{
			ServiceName: "testService",
			IPV4:        "192.228.233.62",
			Port:        80,
		},
		RemoteEndpoint: &models.Endpoint{
			IPV4: "192.228.233.62",
		},
		Tags: map[string]string{
			"http.path": "/api",
		},
	}

	resp, err := zipkin.Operations.PostSpans(
		operations.NewPostSpansParams().WithSpans(models.ListOfSpans{span}),
	)

	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(string(resp.Error()))
}
```

cc @kellabyte @basvanbeek

### CODE REVIEW

**Comment by adriancole** [comment]
PS for those curious, we don't have a read api for this model, yet. the zipkin2 project will take more time to complete, but POST endpoints are available now (in latest 1.30). Follow https://github.com/openzipkin/zipkin/issues/1644 for updates

**Comment by adriancole** [comment]
@flier @ellispritchard you might be interested in this, too

**Comment by adriancole** [comment]
PS I will add more detailed descriptions here as I noticed I had to link people to java files

**Comment by adriancole** [comment]
completed documentation

**Comment by adriancole** [comment]
updated validation script and switched current link to v2

**Comment by adriancole** [comment]
completed documentation

**Comment by ellispritchard** [comment]
Ta @adriancole !

**Comment by adriancole** [comment]
@pavolloffay fyi I know you are working on json and v1 couldn't be code-genned. You may still prefer to not codegen v2, but anyway here's the model for it.

**Comment by pavolloffay** [comment]
@adriancole thanks for pointing to this.

**Pull request merged**
