### PR TITLE
use Sway for validation

### PR DESCRIPTION
**Pull request by mohsen1**
@whitlockjc can you review?

### CODE REVIEW

**Comment by adriancole** [comment]
thx!

**Comment by whitlockjc** [comment]
@adriancole beat me to it, thanks @mohsen1!

**Comment by mohsen1** [comment]
@jamescway for some odd reason it doesn't print anything  See here: https://travis-ci.org/openzipkin/zipkin-api/builds/117364719#L265

No code after `api.validate()` is being executed. Can you guess why?

**Comment by adriancole** [comment]
Whoah.. Cameo appearance by the Whitlock! Thanks for stopping by, Jeremy!

**Comment by whitlockjc** [comment]
I'll help you out anytime @adriancole.

**Pull request merged**
