### PR TITLE
First stab at CircleCI 2.0 migration

### PR DESCRIPTION
**Pull request by abesto**
Based heavily on the work in https://github.com/openzipkin/brave-cassandra/pull/9

The original used the `zulu-9` JDK. Initially I tried running the build on a Docker image with the same JDK, but immediately ran into problems (it's not set up to be a test execution environment); for example there's no `sudo` in the official Zulu 9 image. Note that CircleCI doesn't publish JDK version 9 (see https://hub.docker.com/r/circleci/openjdk/tags/). This PR uses OpenJDK 8, I'm not sure if this causes problems – @adriancole ?

A difference from https://github.com/openzipkin/brave-cassandra/pull/9: instead of messing around with `find` moving test result reports, I tried directly pointing CircleCI at the SureFire output (as theorized in https://github.com/openzipkin/brave/pull/725#discussion_r199327738). Unfortunately this job doesn't actually run any tests (just like the PR in `brave-cassandra`, no tests were run before the migration either), so the result of this change is unconfirmed.

I'll also note here that the build definition is _looooooooooooong_, and I feel error-prone with all the regexes and ignores and so on, and duplicated between many (?) repositories. (Yes, I might have been involved in setting them up originally, I'll still say this is not good). Deduping them is a good area for future research.

### CODE REVIEW

**Comment by shakuzen** [comment]
> Note that CircleCI doesn't publish JDK version 9 (see https://hub.docker.com/r/circleci/openjdk/tags/).

I'm not sure why, but JDK 9 tags are available even though not listed in DockerHub. See, for example, this build: https://circleci.com/gh/openzipkin/brave/1393. That said, we should move to JDK 10 probably since 9 is EOL, but I wanted to just port things as close to the current state as possible first.

> instead of messing around with find moving test result reports, I tried directly pointing CircleCI at the SureFire output

This works fine and is (IMO) preferable if the build is not multi-module. With multi-module projects, the test results are scattered in each of the sub-projects, and this is why we need to collect the reports.

**Comment by abesto** [comment]
> I'm not sure why, but JDK 9 tags are available even though not listed in DockerHub.

Oh wow. It looks like the UI lists a nice round 100 tags, with no paging. Confirming JDK 9 images exist, fixing:

```
$ curl https://registry.hub.docker.com/v1/repositories/circleci/openjdk/tags | jq '.[] | .name' -r | grep '^9'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19998    0 19998    0     0  28527      0 --:--:-- --:--:-- --:--:-- 28527
9
-- SNIP --
9-jdk
9-jdk-browsers
9-jdk-node
-- SNIP --
```

> the 2.0 migration guide tells to rename and move the file to .circleci/config.yml 

Good catch, thanks. Lemme fix that.

**Comment by abesto** [comment]
Build is green; changes were direct fix of review comments, so I won't wait for another round of reviews (let me know if that's against Zipkin practices).

Squash and merge.

**Comment by adriancole** [comment]
what you did is fine!

**Pull request merged**
